.SILENT:    all    clean

all:
	@chmod 0744 exp1.py
	@chmod 0744 exp2.py
	@chmod 0744 exp3.py

clean:
	rm trace_files/1_exp/*.*
	rm trace_files/2_exp/*.*
	rm trace_files/3_exp/*.*
	rm csv_files/1_exp/*.*
	rm csv_files/2_exp/*.*
	rm csv_files/3_exp/*.*
